import { DndClass } from './classes';

export const CLASSES_2014: DndClass[] = [
  {
    id: 'barbarian_2014',
    name: 'Bárbaro',
    description: 'Um guerreiro feroz de origem primitiva que pode entrar em fúria em batalha.',
    image: '/assets/barbarian.png',
    source: "Player's Handbook 2014",
    hitDie: 'd12',
    primaryAttr: 'Força',
    savingThrows: ['Força', 'Constituição'],
    armorProf: 'Armaduras Leves, Médias e Escudos',
    weaponProf: 'Armas Simples e Marciais',
    skillCount: 2,
    skillOptions: ['Adestrar Animais', 'Atletismo', 'Intimidação', 'Natureza', 'Percepção', 'Sobrevivência'],
    features: [
      { name: 'Fúria', level: 1, description: 'Em batalha, você luta com ferocidade primitiva. Você pode entrar em fúria como uma ação bônus.' },
      { name: 'Defesa sem Armadura', level: 1, description: 'Quando não estiver vestindo armadura, sua CA é 10 + Mod. Destreza + Mod. Constituição. Você pode usar um escudo.' },
      { name: 'Ataque Descuidado', level: 2, description: 'No seu primeiro ataque do turno, você pode ganhar vantagem em ataques de Força corpo-a-corpo, mas ataques contra você têm vantagem.' },
      { name: 'Sentido de Perigo', level: 2, description: 'Você tem vantagem em testes de resistência de Destreza contra efeitos que você possa ver.' },
      { name: 'Caminho Primitivo', level: 3, description: 'Escolha um caminho que molda a natureza da sua fúria: Caminho do Furioso ou Caminho do Guerreiro Totêmico.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Ataque Extra', level: 5, description: 'Você pode atacar duas vezes sempre que realizar a ação de Ataque.' },
      { name: 'Movimento Rápido', level: 5, description: 'Seu deslocamento aumenta em 3 metros enquanto não estiver vestindo armadura pesada.' },
      { name: 'Instinto Selvagem', level: 7, description: 'Vantagem em iniciativa. Pode agir surpreso se entrar em fúria primeiro.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Crítico Brutal (1 dado)', level: 9, description: 'Rola um dado de dano extra em um acerto crítico corpo-a-corpo.' },
      { name: 'Fúria Implacável', level: 11, description: 'Ao cair a 0 PV, pode fazer um teste de Con CD 10 para voltar a 1 PV.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Crítico Brutal (2 dados)', level: 13, description: 'Rola dois dados de dano extra em um acerto crítico corpo-a-corpo.' },
      { name: 'Fúria Persistente', level: 15, description: 'Sua fúria só termina prematuramente se você cair inconsciente ou decidir terminá-la.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Crítico Brutal (3 dados)', level: 17, description: 'Rola três dados de dano extra em um acerto crítico corpo-a-corpo.' },
      { name: 'Força Indomável', level: 18, description: 'Se um teste de Força for menor que seu valor de Força, você pode usar o valor do atributo.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Campeão Primitivo', level: 20, description: 'Seus valores de Força e Constituição aumentam em 4, até o máximo de 24.' }
    ]
  },
  {
    id: 'bard_2014',
    name: 'Bardo',
    description: 'Um mestre da música, do entretenimento e da magia, capaz de inspirar seus aliados.',
    image: '/assets/bard.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Carisma',
    savingThrows: ['Destreza', 'Carisma'],
    armorProf: 'Armaduras Leves',
    weaponProf: 'Armas Simples, Bestas de mão, Espadas longas, Rapieiras, Espadas curtas',
    toolProf: 'Três instrumentos musicais à sua escolha',
    skillCount: 3,
    skillOptions: ['Acrobacia', 'Adestrar Animais', 'Arcanismo', 'Atletismo', 'Atuação', 'Enganação', 'Furtividade', 'História', 'Intimidação', 'Intuição', 'Investigação', 'Medicina', 'Natureza', 'Percepção', 'Persuasão', 'Prestidigitação', 'Religião', 'Sobrevivência'],
    features: [
      { name: 'Conjuração', level: 1, description: 'Você pode conjurar magias de bardo usando seu Carisma.' },
      { name: 'Inspiração Bárdica (d6)', level: 1, description: 'Você pode inspirar outros através de palavras ou música como uma ação bônus.' },
      { name: 'Pau para Toda Obra', level: 2, description: 'Você pode adicionar metade do seu bônus de proficiência em qualquer teste de atributo que não possua proficiência.' },
      { name: 'Canção de Descanso (d6)', level: 2, description: 'Você pode ajudar a curar seus aliados durante um descanso curto (1d6).' },
      { name: 'Colégio de Bardo', level: 3, description: 'Escolha um colégio que define suas técnicas: Colégio do Conhecimento ou Colégio da Bravura.' },
      { name: 'Aptidão', level: 3, description: 'Escolha duas perícias proficientes para dobrar seu bônus de proficiência.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Inspiração Bárdica (d8)', level: 5, description: 'Seu dado de inspiração aumenta para d8 e você recupera usos em descansos curtos.' },
      { name: 'Fonte de Inspiração', level: 5, description: 'Você recupera todos os usos de Inspiração Bárdica após um descanso curto ou longo.' },
      { name: 'Canção de Proteção', level: 6, description: 'Use sua música para dar vantagem em testes contra ser amedrontado ou enfeitiçado.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Canção de Descanso (d8)', level: 9, description: 'Sua cura adicional em descansos curtos aumenta para 1d8.' },
      { name: 'Inspiração Bárdica (d10)', level: 10, description: 'Seu dado de inspiração aumenta para d10.' },
      { name: 'Aptidão (Adicional)', level: 10, description: 'Escolha mais duas perícias para ganhar o benefício de Aptidão.' },
      { name: 'Segredos Mágicos', level: 10, description: 'Escolha duas magias de qualquer classe para aprender.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Canção de Descanso (d10)', level: 13, description: 'Sua cura adicional em descansos curtos aumenta para 1d10.' },
      { name: 'Segredos Mágicos (Adicional)', level: 14, description: 'Escolha mais duas magias de qualquer classe para aprender.' },
      { name: 'Inspiração Bárdica (d12)', level: 15, description: 'Seu dado de inspiração aumenta para d12.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Canção de Descanso (d12)', level: 17, description: 'Sua cura adicional em descansos curtos aumenta para 1d12.' },
      { name: 'Segredos Mágicos (Adicional)', level: 18, description: 'Escolha mais duas magias de qualquer classe para aprender.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Inspiração Superior', level: 20, description: 'Se rolar iniciativa sem usos de Inspiração Bárdica, recupera um uso.' }
    ]
  },
  {
    id: 'cleric_2014',
    name: 'Clérigo',
    description: 'Um campeão sacerdotal que utiliza magia divina a serviço de um poder superior.',
    image: '/assets/cleric.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Sabedoria',
    savingThrows: ['Sabedoria', 'Carisma'],
    armorProf: 'Armaduras Leves, Médias e Escudos',
    weaponProf: 'Armas Simples',
    skillCount: 2,
    skillOptions: ['História', 'Intuição', 'Medicina', 'Persuasão', 'Religião'],
    features: [
      { name: 'Conjuração', level: 1, description: 'Você pode conjurar magias de clérigo usando sua Sabedoria.' },
      { name: 'Domínio Divino', level: 1, description: 'Escolha um domínio relacionado à sua divindade. Concede magias e habilidades específicas.' },
      { name: 'Canalizar Divindade (1/descanso)', level: 2, description: 'Você pode canalizar energia divina para criar efeitos mágicos, como Expulsar Mortos-vivos.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Destruir Mortos-Vivos (ND 1/2)', level: 5, description: 'Mortos-vivos que falharem na expulsão são destruídos se o ND for 1/2 ou menor.' },
      { name: 'Canalizar Divindade (2/descanso)', level: 6, description: 'Você pode usar Canalizar Divindade duas vezes entre descansos.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Destruir Mortos-Vivos (ND 1)', level: 8, description: 'Destrói mortos-vivos de ND 1 ou menor.' },
      { name: 'Intervenção Divina', level: 10, description: 'Você pode rogar à sua divindade por auxílio. Rola d% (sucesso se <= nível).' },
      { name: 'Destruir Mortos-Vivos (ND 2)', level: 11, description: 'Destrói mortos-vivos de ND 2 ou menor.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Destruir Mortos-Vivos (ND 3)', level: 14, description: 'Destrói mortos-vivos de ND 3 ou menor.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Destruir Mortos-Vivos (ND 4)', level: 17, description: 'Destrói mortos-vivos de ND 4 ou menor.' },
      { name: 'Canalizar Divindade (3/descanso)', level: 18, description: 'Você pode usar Canalizar Divindade três vezes entre descansos.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Aprimoramento de Intervenção Divina', level: 20, description: 'Seu pedido de intervenção divina funciona automaticamente.' }
    ]
  },
  {
    id: 'druid_2014',
    name: 'Druida',
    description: 'Um místico que abraça as forças da natureza, capaz de assumir formas animais.',
    image: '/assets/druid.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Sabedoria',
    savingThrows: ['Inteligência', 'Sabedoria'],
    armorProf: 'Armaduras Leves, Médias e Escudos (não metálicos)',
    weaponProf: 'Bordão, Adaga, Dardo, Azagaia, Maça, Foice, Cimitarra, Funda, Lança',
    skillCount: 2,
    skillOptions: ['Arcanismo', 'Adestrar Animais', 'Intuição', 'Medicina', 'Natureza', 'Percepção', 'Religião', 'Sobrevivência'],
    features: [
      { name: 'Druídico', level: 1, description: 'Você conhece o idioma secreto dos druidas.' },
      { name: 'Conjuração', level: 1, description: 'Você pode conjurar magias de druida usando sua Sabedoria.' },
      { name: 'Forma Selvagem', level: 2, description: 'Você pode assumir a forma de uma fera que você já tenha visto.' },
      { name: 'Círculo Druídico', level: 2, description: 'Escolha um círculo druídico: Círculo da Terra ou Círculo da Lua.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Melhoria na Forma Selvagem (ND 1/2)', level: 4, description: 'Você pode se transformar em criaturas de ND 1/2 que não possuam deslocamento de voo.' },
      { name: 'Característica de Círculo', level: 6, description: 'Você ganha uma nova característica baseada no seu Círculo Druídico.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Melhoria na Forma Selvagem (ND 1)', level: 8, description: 'Você pode se transformar em criaturas de ND 1, incluindo criaturas voadoras.' },
      { name: 'Característica de Círculo', level: 10, description: 'Você ganha uma nova característica baseada no seu Círculo Druídico.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Círculo', level: 14, description: 'Você ganha a característica final baseada no seu Círculo Druídico.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Corpo Atemporal', level: 18, description: 'Para cada 10 anos que passarem, seu corpo envelhece apenas 1 ano.' },
      { name: 'Conjuração de Besta', level: 18, description: 'Você pode conjurar magias em forma selvagem que possuam apenas componentes verbais e somáticos.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Arquidruida', level: 20, description: 'Você pode usar Forma Selvagem um número ilimitado de vezes.' }
    ]
  },
  {
    id: 'fighter_2014',
    name: 'Guerreiro',
    description: 'Um mestre do combate, proficiente com uma ampla variedade de armas e armaduras.',
    image: '/assets/warrior.png',
    source: "Player's Handbook 2014",
    hitDie: 'd10',
    primaryAttr: 'Força ou Destreza',
    savingThrows: ['Força', 'Constituição'],
    armorProf: 'Todas as Armaduras e Escudos',
    weaponProf: 'Armas Simples e Marciais',
    skillCount: 2,
    skillOptions: ['Acrobacia', 'Adestrar Animais', 'Atletismo', 'História', 'Intuição', 'Intimidação', 'Percepção', 'Sobrevivência'],
    features: [
      { name: 'Estilo de Luta', level: 1, description: 'Você adota um estilo de combate particular como sua especialidade (Arquearia, Defesa, Duelismo, etc).' },
      { name: 'Retomar o Fôlego', level: 1, description: 'Você pode usar uma ação bônus para recuperar pontos de vida igual a 1d10 + seu nível de guerreiro.' },
      { name: 'Surto de Ação', level: 2, description: 'Você pode realizar uma ação adicional juntamente com sua ação e possível ação bônus. (2 usos no nível 17)' },
      { name: 'Arquétipo Marcial', level: 3, description: 'Escolha um arquétipo: Campeão, Cavaleiro Arcano ou Mestre de Batalha.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Ataque Extra', level: 5, description: 'Você pode atacar duas vezes sempre que realizar a ação de Ataque.' },
      { name: 'Incremento no Valor de Habilidade', level: 6, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Arquétipo', level: 7, description: 'Você ganha uma nova característica baseada no seu Arquétipo Marcial.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Indomável', level: 9, description: 'Você pode jogar de novo um teste de resistência que falhou. (2 usos no nível 13, 3 usos no nível 17)' },
      { name: 'Característica de Arquétipo', level: 10, description: 'Você ganha uma nova característica baseada no seu Arquétipo Marcial.' },
      { name: 'Ataque Extra (2)', level: 11, description: 'Você pode atacar três vezes sempre que realizar a ação de Ataque.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Indomável (2 usos)', level: 13, description: 'Você pode usar Indomável duas vezes entre descansos longos.' },
      { name: 'Incremento no Valor de Habilidade', level: 14, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Arquétipo', level: 15, description: 'Você ganha uma nova característica baseada no seu Arquétipo Marcial.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Surto de Ação (2 usos)', level: 17, description: 'Você pode usar Surto de Ação duas vezes entre descansos.' },
      { name: 'Indomável (3 usos)', level: 17, description: 'Você pode usar Indomável três vezes entre descansos longos.' },
      { name: 'Característica de Arquétipo', level: 18, description: 'Você ganha a característica final do seu Arquétipo Marcial.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Ataque Extra (3)', level: 20, description: 'Você pode atacar quatro vezes sempre que realizar a ação de Ataque.' }
    ]
  },
  {
    id: 'monk_2014',
    name: 'Monge',
    description: 'Um mestre das artes marciais, capaz de utilizar a energia do Ki para feitos sobre-humanos.',
    image: '/assets/monk.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Destreza e Sabedoria',
    savingThrows: ['Força', 'Destreza'],
    armorProf: 'Nenhuma',
    weaponProf: 'Armas Simples e Espadas Curtas',
    toolProf: 'Um tipo de ferramenta de artesão ou um instrumento musical à sua escolha',
    skillCount: 2,
    skillOptions: ['Acrobacia', 'Atletismo', 'História', 'Intuição', 'Religião', 'Furtividade'],
    features: [
      { name: 'Defesa sem Armadura', level: 1, description: 'Sua CA is 10 + Mod. Des + Mod. Sab.' },
      { name: 'Artes Marciais', level: 1, description: 'Você pode usar Destreza ao invés de Força para as jogadas de ataque e dano dos seus golpes desarmados e de suas armas de monge.' },
      { name: 'Chi', level: 2, description: 'Você pode canalizar a energia mística do chi para realizar feitos extraordinários.' },
      { name: 'Movimento sem Armadura', level: 2, description: 'Seu deslocamento aumenta em 3 metros enquanto você não estiver usando armadura nem empunhando um escudo.' },
      { name: 'Tradição Monástica', level: 3, description: 'Escolha uma tradição: Caminho da Mão Aberta, Caminho da Sombra ou Caminho dos Quatro Elementos.' },
      { name: 'Defletir Projéteis', level: 3, description: 'Você pode usar sua reação para defletir ou apanhar o projétil quando você é atingido por um ataque de arma à distância.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Queda Lenta', level: 4, description: 'Você pode usar sua reação, quando você cai, para reduzir o dano de queda sofrido por um valor igual a cinco vezes seu nível de monge.' },
      { name: 'Ataque Extra', level: 5, description: 'Você pode atacar duas vezes, ao invés de uma, sempre que você realizar a ação de Ataque no seu turno.' },
      { name: 'Ataque Atordoante', level: 5, description: 'Você pode gastar 1 ponto de chi para tentar um ataque atordoante (CD de resistência de Chi).' },
      { name: 'Golpes de Chi', level: 6, description: 'Seus golpes desarmados contam como armas mágicas com o propósito de ultrapassar resistência ou imunidade.' },
      { name: 'Característica de Tradição Monástica', level: 6, description: 'Você ganha uma nova característica baseada na sua Tradição Monástica.' },
      { name: 'Evasão', level: 7, description: 'Você não sofre dano algum se passar num teste de Destreza para metade do dano, e somente metade se falhar.' },
      { name: 'Mente Tranquila', level: 7, description: 'Você pode usar sua ação para terminar um efeito em si mesmo, que esteja lhe enfeitiçando ou amedrontando.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Aprimoramento de Movimento sem Armadura', level: 9, description: 'Você ganha a habilidade de se mover através de superfícies verticais e sobre líquidos sem cair.' },
      { name: 'Pureza Corporal', level: 10, description: 'Você se torna imune a doenças e venenos.' },
      { name: 'Característica de Tradição Monástica', level: 11, description: 'Você ganha uma nova característica baseada na sua Tradição Monástica.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Idiomas do Sol e da Lua', level: 13, description: 'Você compreende todos os idiomas falados e qualquer criatura pode entender o que você fala.' },
      { name: 'Alma de Diamante', level: 14, description: 'Você ganha proficiência em todos os testes de resistência.' },
      { name: 'Corpo Atemporal', level: 15, description: 'Você não sofre os efeitos da velhice, não pode envelhecer magicamente e não precisa de comida ou água.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Tradição Monástica', level: 17, description: 'Você ganha a característica final da sua Tradição Monástica.' },
      { name: 'Corpo Vazio', level: 18, description: 'Você pode gastar 4 pontos de chi para ficar invisível por 1 minuto e ganhar resistência a danos exceto energia.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Auto Aperfeiçoamento', level: 20, description: 'Se rolar iniciativa e não tiver nenhum ponto de chi restante, você recupera 4 pontos de chi.' }
    ]
  },
  {
    id: 'paladin_2014',
    name: 'Paladino',
    description: 'Um guerreiro sagrado vinculado por um juramento inabalável.',
    image: '/assets/paladin.png',
    source: "Player's Handbook 2014",
    hitDie: 'd10',
    primaryAttr: 'Força e Carisma',
    savingThrows: ['Sabedoria', 'Carisma'],
    armorProf: 'Todas as Armaduras e Escudos',
    weaponProf: 'Armas Simples e Marciais',
    skillCount: 2,
    skillOptions: ['Atletismo', 'Intuição', 'Intimidação', 'Medicina', 'Persuasão', 'Religião'],
    features: [
      { name: 'Sentido Divino', level: 1, description: 'Com uma ação, detecta localização de celestiais, corruptores ou mortos-vivos a até 18m.' },
      { name: 'Cura pelas Mãos', level: 1, description: 'Você tem um poço de poder curativo igual ao seu nível x 5.' },
      { name: 'Estilo de Luta', level: 2, description: 'Escolha: Combate com Armas Grandes, Defesa, Duelismo ou Proteção.' },
      { name: 'Conjuração', level: 2, description: 'Você prepara magias de paladino iguais ao seu Mod. Carisma + metade do seu nível.' },
      { name: 'Destruição Divina', level: 2, description: 'Gaste um espaço de magia para causar dano radiante extra (2d8 para 1º nível, +1d8/nível extra).' },
      { name: 'Saúde Divina', level: 3, description: 'Você se torna imune a doenças.' },
      { name: 'Juramento Sagrado', level: 3, description: 'Escolha: Juramento de Devoção, Juramento dos Anciãos ou Juramento de Vingança.' },
      { name: 'Canalizar Divindade', level: 3, description: 'Você ganha opções de Canalizar Divindade baseadas no seu juramento.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Ataque Extra', level: 5, description: 'Você pode atacar duas vezes sempre que realizar a ação de Ataque.' },
      { name: 'Aura de Proteção', level: 6, description: 'Aliados a até 3 metros ganham bônus em salvaguardas igual ao seu Carisma.' },
      { name: 'Característica de Juramento Sagrado', level: 7, description: 'Você ganha uma nova característica baseada no seu Juramento Sagrado.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Aura de Coragem', level: 10, description: 'Aliados a até 3 metros não podem ser amedrontados enquanto estiver consciente.' },
      { name: 'Destruição Divina Aprimorada', level: 11, description: 'Seus ataques corpo-a-corpo causam 1d8 de dano radiante extra.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Toque Purificador', level: 14, description: 'Você pode remover uma magia em si mesmo ou em um aliado voluntário com um toque.' },
      { name: 'Característica de Juramento Sagrado', level: 15, description: 'Você ganha uma nova característica baseada no seu Juramento Sagrado.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Aprimoramentos de Aura', level: 18, description: 'O alcance de suas auras aumenta para 9 metros.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Juramento Sagrado', level: 20, description: 'Você ganha a característica final do seu Juramento Sagrado.' }
    ]
  },
  {
    id: 'ranger_2014',
    name: 'Patrulheiro',
    description: 'Um mestre da sobrevivência e do combate em áreas selvagens.',
    image: '/assets/ranger.png',
    source: "Player's Handbook 2014",
    hitDie: 'd10',
    primaryAttr: 'Destreza e Sabedoria',
    savingThrows: ['Força', 'Destreza'],
    armorProf: 'Armaduras Leves, Médias e Escudos',
    weaponProf: 'Armas Simples e Marciais',
    skillCount: 3,
    skillOptions: ['Adestrar Animais', 'Atletismo', 'Intuição', 'Investigação', 'Natureza', 'Percepção', 'Furtividade', 'Sobrevivência'],
    features: [
      { name: 'Inimigo Favorito', level: 1, description: 'Você ganha +2 de bônus nas jogadas de dano contra o tipo escolhido e vantagem em testes para rastrear e obter informações.' },
      { name: 'Explorador Natural', level: 1, description: 'Você ignora terreno difícil, tem vantagem em iniciativa e vantagem em ataques contra quem ainda não agiu no 1º turno.' },
      { name: 'Estilo de Luta', level: 2, description: 'Você adota um estilo de combate particular como sua especialidade (Arquearia, Combate com Duas Armas, Defesa ou Duelismo).' },
      { name: 'Conjuração', level: 2, description: 'Você aprende a usar a essência mágica da natureza para conjurar magias.' },
      { name: 'Conclave de Patrulheiro', level: 3, description: 'Você escolhe emular os ideais de um conclave: Besta, Caçador ou Rastreador Subterrâneo.' },
      { name: 'Consciência Primitiva', level: 3, description: 'Você pode se comunicar com bestas e sentir a presença de seus inimigos favoritos a até 8 km.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Conclave', level: 5, description: 'Você ganha uma característica baseada no seu Conclave (ex: Ataque Extra ou Ataque Coordenado).' },
      { name: 'Inimigo Favorito Maior', level: 6, description: 'Escolha um novo tipo de inimigo. Seu bônus de dano contra todos os inimigos favoritos aumenta para +4.' },
      { name: 'Característica de Conclave', level: 7, description: 'Você ganha uma nova característica defensiva baseada no seu Conclave.' },
      { name: 'Pés Rápidos', level: 8, description: 'Você pode usar a ação de Disparada como uma ação bônus no seu turno.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Mimetismo', level: 10, description: 'Se você permanecer imóvel, inimigos sofrem -10 de penalidade para detectar você.' },
      { name: 'Característica de Conclave', level: 11, description: 'Você ganha uma nova característica de ataque múltiplo baseada no seu Conclave.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Desaparecer', level: 14, description: 'Você pode usar a ação de Esconder como uma ação bônus e não pode ser rastreado por meios não mágicos.' },
      { name: 'Característica de Conclave', level: 15, description: 'Você ganha uma característica defensiva superior baseada no seu Conclave.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Sentidos Selvagens', level: 18, description: 'Você luta contra criaturas que não pode ver sem desvantagem e detecta criaturas invisíveis a até 9 metros.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Matador de Inimigos', level: 20, description: 'Uma vez por turno, adicione seu modificador de Sabedoria na jogada de ataque ou de dano contra um inimigo.' }
    ]
  },
  {
    id: 'rogue_2014',
    name: 'Ladino',
    description: 'Um mestre da furtividade e da precisão, capaz de encontrar pontos fracos em qualquer defesa.',
    image: '/assets/rogue.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Destreza',
    savingThrows: ['Destreza', 'Inteligência'],
    armorProf: 'Armaduras Leves',
    weaponProf: 'Armas Simples, Bestas de mão, Espadas longas, Rapieiras, Espadas curtas',
    toolProf: 'Ferramentas de ladrão',
    skillCount: 4,
    skillOptions: ['Acrobacia', 'Atletismo', 'Enganação', 'Intuição', 'Intimidação', 'Investigação', 'Percepção', 'Atuação', 'Persuasão', 'Prestidigitação', 'Furtividade'],
    features: [
      { name: 'Especialização', level: 1, description: 'Você escolhe duas de suas proficiências em perícias para dobrar seu bônus de proficiência.' },
      { name: 'Ataque Furtivo', level: 1, description: 'Você causa dano extra ao atingir uma criatura com vantagem ou se houver um aliado próximo.' },
      { name: 'Gíria de Ladrão', level: 1, description: 'Você conhece o jargão e códigos secretos que permitem passar mensagens ocultas.' },
      { name: 'Ação Ardilosa', level: 2, description: 'Você pode usar uma ação bônus em cada turno para Disparada, Desengajar ou Esconder.' },
      { name: 'Arquétipo Ladino', level: 3, description: 'Escolha um arquétipo: Assassino ou Ladrão.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Esquiva Sobrenatural', level: 5, description: 'Quando um atacante que você possa ver atinge você, pode usar sua reação para reduzir o dano pela metade.' },
      { name: 'Especialização (Adicional)', level: 6, description: 'Escolha mais duas perícias para dobrar seu bônus de proficiência.' },
      { name: 'Evasão', level: 7, description: 'Você não sofre dano em sucessos de Destreza e apenas metade em falhas.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Arquétipo', level: 9, description: 'Você ganha uma nova característica baseada no seu Arquétipo Ladino.' },
      { name: 'Incremento no Valor de Habilidade', level: 10, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Talento Confiável', level: 11, description: 'Sempre que fizer um teste com uma perícia proficiente, um resultado de 9 ou menos no d20 torna-se 10.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Arquétipo', level: 13, description: 'Você ganha uma nova característica baseada no seu Arquétipo Ladino.' },
      { name: 'Sentido Cego', level: 14, description: 'Você percebe qualquer criatura oculta ou invisível a até 3 metros.' },
      { name: 'Mente Escorregadia', level: 15, description: 'Você ganha proficiência em testes de resistência de Sabedoria.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Arquétipo', level: 17, description: 'Você ganha a característica final baseada no seu Arquétipo Ladino.' },
      { name: 'Elusivo', level: 18, description: 'Nenhuma jogada de ataque tem vantagem contra você enquanto você não estiver incapacitado.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Golpe de Sorte', level: 20, description: 'Se você errar um ataque ou falhar em um teste, pode transformar o resultado em um sucesso automático (1x/descanso).' }
    ]
  },
  {
    id: 'sorcerer_2014',
    name: 'Feiticeiro',
    description: 'Um conjurador nato, cujo poder deriva de uma linhagem mágica ou influência exótica.',
    image: '/assets/sorcerer.png',
    source: "Player's Handbook 2014",
    hitDie: 'd6',
    primaryAttr: 'Carisma',
    savingThrows: ['Constituição', 'Carisma'],
    armorProf: 'Nenhuma',
    weaponProf: 'Adagas, Dardos, Fundas, Bordões, Bestas leves',
    skillCount: 2,
    skillOptions: ['Arcanismo', 'Enganação', 'Intuição', 'Intimidação', 'Persuasão', 'Religião'],
    features: [
      { name: 'Conjuração', level: 1, description: 'Você pode conjurar magias de feiticeiro usando seu Carisma como habilidade de conjuração.' },
      { name: 'Origem de Feitiçaria', level: 1, description: 'Escolha a fonte do seu poder mágico inato: Linhagem Dracônica ou Magia Selvagem.' },
      { name: 'Fonte de Magia', level: 2, description: 'Você possui pontos de feitiçaria que permitem criar espaços de magia ou alterar suas magias.' },
      { name: 'Metamágica', level: 3, description: 'Você ganha a habilidade de distorcer suas magias (ex: Magia Sutil, Acelerada, Duplicada).' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Origem', level: 6, description: 'Você ganha uma nova característica baseada na sua Origem de Feitiçaria.' },
      { name: 'Metamágica (Adicional)', level: 10, description: 'Você escolhe uma terceira opção de Metamágica.' },
      { name: 'Característica de Origem', level: 14, description: 'Você ganha uma nova característica baseada na sua Origem de Feitiçaria.' },
      { name: 'Metamágica (Adicional)', level: 17, description: 'Você escolhe uma quarta opção de Metamágica.' },
      { name: 'Característica de Origem', level: 18, description: 'Você ganha uma nova característica baseada na sua Origem de Feitiçaria.' },
      { name: 'Restauração Mística', level: 20, description: 'Você recupera 4 pontos de feitiçaria gastos sempre que terminar um descanso curto.' }
    ]
  },
  {
    id: 'warlock_2014',
    name: 'Bruxo',
    description: 'Um buscador de conhecimento proibido que fez um pacto com uma entidade poderosa.',
    image: '/assets/warlock.png',
    source: "Player's Handbook 2014",
    hitDie: 'd8',
    primaryAttr: 'Carisma',
    savingThrows: ['Sabedoria', 'Carisma'],
    armorProf: 'Armaduras Leves',
    weaponProf: 'Armas Simples',
    skillCount: 2,
    skillOptions: ['Arcanismo', 'Enganação', 'História', 'Intimidação', 'Investigação', 'Natureza', 'Religião'],
    features: [
      { name: 'Patrono Transcendental', level: 1, description: 'Você fez um pacto com um ser de outro plano de existência: A Arquifada, O Corruptor ou O Grande Antigo.' },
      { name: 'Magia de Pacto', level: 1, description: 'Sua magia é concedida por seu patrono e você recupera seus espaços de magia em descansos curtos.' },
      { name: 'Invocações Místicas', level: 2, description: 'Você descobriu segredos ocultos que te concedem habilidades mágicas permanentes.' },
      { name: 'Dádiva do Pacto', level: 3, description: 'Seu patrono lhe confere um dom: Pacto da Corrente, Pacto da Lâmina ou Pacto do Tomo.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Patrono Transcendental', level: 6, description: 'Você ganha uma nova característica concedida pelo seu patrono.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Patrono Transcendental', level: 10, description: 'Você ganha uma nova característica concedida pelo seu patrono.' },
      { name: 'Arcana Mística (6° nível)', level: 11, description: 'Seu patrono confere a você um segredo mágico (uma magia de 6° nível).' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Arcana Mística (7° nível)', level: 13, description: 'Seu patrono confere a você um segredo mágico (uma magia de 7° nível).' },
      { name: 'Característica de Patrono Transcendental', level: 14, description: 'Você ganha uma nova característica concedida pelo seu patrono.' },
      { name: 'Arcana Mística (8° nível)', level: 15, description: 'Seu patrono confere a você um segredo mágico (uma magia de 8° nível).' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Arcana Mística (9° nível)', level: 17, description: 'Seu patrono confere a você um segredo mágico (uma magia de 9° nível).' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Mestre Místico', level: 20, description: 'Você pode recuperar todos os seus espaços de magia de pacto em 1 minuto.' }
    ]
  },
  {
    id: 'wizard_2014',
    name: 'Mago',
    description: 'Um estudioso acadêmico da magia, capaz de manipular a realidade através de fórmulas e rituais.',
    image: '/assets/wizard.png',
    source: "Player's Handbook 2014",
    hitDie: 'd6',
    primaryAttr: 'Inteligência',
    savingThrows: ['Inteligência', 'Sabedoria'],
    armorProf: 'Nenhuma',
    weaponProf: 'Adagas, Dardos, Fundas, Bordões, Bestas leves',
    skillCount: 2,
    skillOptions: ['Arcanismo', 'História', 'Intuição', 'Investigação', 'Medicina', 'Religião'],
    features: [
      { name: 'Conjuração', level: 1, description: 'Você pode conjurar magias de mago usando sua Inteligência.' },
      { name: 'Recuperação Arcana', level: 1, description: 'Você recupera espaços de magia igual a metade do seu nível em um descanso curto.' },
      { name: 'Grimório', level: 1, description: 'Você possui um livro contendo as fórmulas de suas magias.' },
      { name: 'Tradição Arcana', level: 2, description: 'Escolha uma das oito escolas: Abjuração, Adivinhação, Conjuração, Encantamento, Evocação, Ilusão, Necromancia ou Transmutação.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Tradição Arcana', level: 6, description: 'Você ganha uma nova característica baseada na sua Tradição Arcana.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Tradição Arcana', level: 10, description: 'Você ganha uma nova característica baseada na sua Tradição Arcana.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Tradição Arcana', level: 14, description: 'Você ganha a característica final baseada na sua Tradição Arcana.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Dominar Magia', level: 18, description: 'Escolha uma magia de 1º e uma de 2º círculo para conjurar sem gastar espaços.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Assinatura Mágica', level: 20, description: 'Escolha duas magias de 3º círculo que você pode conjurar uma vez cada sem gastar espaços.' }
    ]
  },
  {
    id: 'artificer_2014',
    name: 'Artífice',
    description: 'Um mestre da invenção e da engenharia mágica, capaz de imbuir itens comuns com poder arcano.',
    image: '/assets/artificer.png',
    source: "Tasha's Cauldron of Everything",
    hitDie: 'd8',
    primaryAttr: 'Inteligência',
    savingThrows: ['Constituição', 'Inteligência'],
    armorProf: 'Armaduras Leves, Médias e Escudos',
    weaponProf: 'Armas Simples',
    toolProf: 'Ferramentas de ladrão, ferramentas de funileiro, um tipo de ferramenta de artesão à sua escolha',
    skillCount: 2,
    skillOptions: ['Arcanismo', 'História', 'Investigação', 'Medicina', 'Natureza', 'Percepção', 'Prestidigitação'],
    features: [
      { name: 'Conjuração', level: 1, description: 'Você aprendeu a canalizar magia através de ferramentas e objetos.' },
      { name: 'Engenharia Mágica', level: 1, description: 'Você pode imbuir propriedades mágicas em objetos minúsculos não mágicos.' },
      { name: 'Infundir Item', level: 2, description: 'Você ganha a habilidade de imbuir itens mundanos com infusões mágicas.' },
      { name: 'Especialização de Artífice', level: 3, description: 'Escolha uma especialização: Alquimista, Armeiro, Atirador ou Ferreiro de Batalha.' },
      { name: 'A Ferramenta Certa para o Trabalho', level: 3, description: 'Você pode criar magicamente um conjunto de ferramentas de artesão que você precise.' },
      { name: 'Incremento no Valor de Habilidade', level: 4, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Especialização', level: 5, description: 'Você ganha uma característica da sua especialização escolhida.' },
      { name: 'Maestria em Ferramenta', level: 6, description: 'Seu bônus de proficiência é dobrado para qualquer teste com ferramentas que você seja proficiente.' },
      { name: 'Infusões de Artífice (6 conhecidas, 3 itens)', level: 6, description: 'Você aprende novas infusões e pode manter mais itens infundidos simultaneamente.' },
      { name: 'Lampejo de Genialidade', level: 7, description: 'Você pode adicionar seu modificador de Inteligência ao teste de habilidade ou salvaguarda de alguém.' },
      { name: 'Incremento no Valor de Habilidade', level: 8, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Característica de Especialização', level: 9, description: 'Você ganha uma nova característica da sua especialização escolhida.' },
      { name: 'Perito em Itens Mágicos', level: 10, description: 'Você pode se sintonizar com até quatro itens mágicos; criação de itens comuns/incomuns é mais rápida e barata.' },
      { name: 'Infusões de Artífice (8 conhecidas, 4 itens)', level: 10, description: 'Você aprende novas infusões e pode manter mais itens infundidos simultaneamente.' },
      { name: 'Item de Armazenar Magia', level: 11, description: 'Você pode armazenar uma magia de 1º ou 2º círculo em um objeto para uso posterior.' },
      { name: 'Incremento no Valor de Habilidade', level: 12, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Versado em Itens Mágicos', level: 14, description: 'Você pode se sintonizar com até cinco itens mágicos e ignora requisitos de classe/raça/nível.' },
      { name: 'Infusões de Artífice (10 conhecidas, 5 itens)', level: 14, description: 'Você aprende novas infusões e pode manter mais itens infundidos simultaneamente.' },
      { name: 'Característica de Especialização', level: 15, description: 'Você ganha a característica final da sua especialização escolhida.' },
      { name: 'Incremento no Valor de Habilidade', level: 16, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Maestria em Itens Mágicos', level: 18, description: 'Você pode se sintonizar com até seis itens mágicos de uma vez.' },
      { name: 'Infusões de Artífice (12 conhecidas, 6 itens)', level: 18, description: 'Você aprende novas infusões e pode manter mais itens infundidos simultaneamente.' },
      { name: 'Incremento no Valor de Habilidade', level: 19, description: 'Aumente um valor de habilidade em 2 ou dois valores em 1.' },
      { name: 'Alma do Artífice', level: 20, description: 'Você ganha bônus em salvaguardas por item sintonizado e pode evitar a morte encerrando uma infusão.' }
    ]
  }
];

