export type SpellSchool =
  | 'Abjuração' | 'Adivinhação' | 'Conjuração' | 'Encantamento'
  | 'Evocação' | 'Ilusão' | 'Necromancia' | 'Transmutação'

export interface Spell {
  id: string
  name: string
  level: number   // 0 = cantrip
  school: SpellSchool
  castingTime: string
  duration: string
  range: string
  components: string
  description: string
  damageEffect: string
  attackSave?: string
  classes: string[]
  ritual?: boolean
  concentration?: boolean
}

const SPELLS: Spell[] = [
  // ── Cantrips ────────────────────────────────────────────────────────────────
  { id: 'acid-splash', name: 'Esguicho de Ácido', level: 0, school: 'Conjuração', castingTime: '1 ação', duration: 'Instantânea', range: '18 m', components: 'V, S', description: 'Você conjura uma bolha de ácido. Escolha uma criatura dentro do alcance para fazer um teste de resistência de Destreza. Se falhar, sofre 1d6 de dano ácido.', damageEffect: '1d6 Ácido', attackSave: 'Res. Des', classes: ['Mago', 'Feiticeiro'] },
  { id: 'blade-ward', name: 'Guarda da Lâmina', level: 0, school: 'Abjuração', castingTime: '1 ação', duration: '1 rodada', range: 'Pessoal', components: 'V, S', description: 'Você estende sua mão e traça um signo de proteção. Até o final do próximo turno você tem resistência contra dano perfurante, cortante e concussão das armas.', damageEffect: 'Proteção', classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago', 'Artesão Arcano'] },
  { id: 'chill-touch', name: 'Toque Glacial', level: 0, school: 'Necromancia', castingTime: '1 ação', duration: '1 rodada', range: '36 m', components: 'V, S', description: 'Você cria uma mão espectral de uma criatura não morta e a manda atacar uma criatura dentro do alcance. Faça um ataque mágico a distância. Se acertar, sofre 1d8 necrótico e não pode recuperar PV até o início de seu próximo turno.', damageEffect: '1d8 Necrótico', attackSave: 'Ataque', classes: ['Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'dancing-lights', name: 'Luzes Dançantes', level: 0, school: 'Evocação', castingTime: '1 ação', duration: '1 min', range: '36 m', components: 'V, S, M', description: 'Você cria até quatro luzes de tamanho tocha dentro do alcance. Elas podem ser movidas 18 m como ação bônus.', damageEffect: 'Utilidade', concentration: true, classes: ['Bardo', 'Feiticeiro', 'Mago', 'Artesão Arcano'] },
  { id: 'druidcraft', name: 'Artesanato Druídico', level: 0, school: 'Transmutação', castingTime: '1 ação', duration: 'Instantânea', range: '5 m', components: 'V, S', description: 'Sussurra com a natureza: prevê o tempo, faz flores desabrocharem, acende ou apaga velas, cria um efeito sensorial inofensivo.', damageEffect: 'Utilidade', classes: ['Druida'] },
  { id: 'eldritch-blast', name: 'Descarga Sobrenatural', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '36 m', components: 'V, S', description: 'Um feixe de energia reluzente açoita uma criatura dentro do alcance. Faça um ataque mágico à distância. Em um acerto, o alvo sofre 1d10 de dano de força.', damageEffect: '1d10 Força', attackSave: 'Ataque', classes: ['Bruxo'] },
  { id: 'fire-bolt', name: 'Raio de Fogo', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '36 m', components: 'V, S', description: 'Você arremessa um feixe incandescente em uma criatura ou objeto dentro do alcance. Faça um ataque mágico à distância. Em um acerto, o alvo sofre 1d10 de dano de fogo.', damageEffect: '1d10 Fogo', attackSave: 'Ataque', classes: ['Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'friends', name: 'Amigos', level: 0, school: 'Encantamento', castingTime: '1 ação', duration: '1 min', range: 'Pessoal', components: 'S, M', description: 'Durante a duração, você tem vantagem em todos os testes de Carisma feitos contra uma criatura não hostil que você possa ver.', damageEffect: 'Social', concentration: true, classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'guidance', name: 'Orientação', level: 0, school: 'Adivinhação', castingTime: '1 ação', duration: '1 min', range: 'Toque', components: 'V, S', description: 'Você toca uma criatura voluntária. Uma vez antes da magia terminar, o alvo pode rolar 1d4 e adicionar o número a um teste de habilidade.', damageEffect: '+1d4 em teste', concentration: true, classes: ['Clérigo', 'Druida'] },
  { id: 'light', name: 'Luz', level: 0, school: 'Evocação', castingTime: '1 ação', duration: '1 hora', range: 'Toque', components: 'V, M', description: 'Você toca um objeto de até 3 metros. Ele emite luz brilhante em um raio de 6 metros e penumbra por mais 6 metros.', damageEffect: 'Utilidade', classes: ['Bardo', 'Clérigo', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'mage-hand', name: 'Mão Mágica', level: 0, school: 'Conjuração', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'V, S', description: 'Uma mão espectral flutuante aparece no ponto escolhido. Pode manipular objetos simples, abrir portas e recipientes, guardar ou pegar itens de recipientes.', damageEffect: 'Utilidade', classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago', 'Artesão Arcano'] },
  { id: 'mending', name: 'Conserto', level: 0, school: 'Transmutação', castingTime: '1 min', duration: 'Instantânea', range: 'Toque', components: 'V, S, M', description: 'Este truque repara uma única interrupção ou fratura em um objeto que você toca, como uma corrente partida, duas metades de uma chave partida ou um goblet rachado.', damageEffect: 'Utilidade', classes: ['Bardo', 'Clérigo', 'Druida', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'message', name: 'Mensagem', level: 0, school: 'Transmutação', castingTime: '1 ação', duration: '1 rodada', range: '36 m', components: 'V, S, M', description: 'Você aponta para uma criatura dentro do alcance e sussurra uma mensagem. O alvo (e só o alvo) ouve a mensagem e pode responder com um sussurro.', damageEffect: 'Comunicação', classes: ['Bardo', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'minor-illusion', name: 'Ilusão Menor', level: 0, school: 'Ilusão', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'S, M', description: 'Você cria um som ou uma imagem de um objeto dentro do alcance que dura pelo período. A ilusão termina se você a descartar (ação bônus) ou conjurar essa magia de novo.', damageEffect: 'Ilusão', classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'poison-spray', name: 'Névoa Venenosa', level: 0, school: 'Conjuração', castingTime: '1 ação', duration: 'Instantânea', range: '3 m', components: 'V, S', description: 'Você estende a mão e projeta uma bolha de veneno podre de sua palma. A criatura deve ser bem-sucedida em um teste de resistência de Constituição ou recebe 1d12 de dano de veneno.', damageEffect: '1d12 Veneno', attackSave: 'Res. Con', classes: ['Druida', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'prestidigitation', name: 'Prestidigitação', level: 0, school: 'Transmutação', castingTime: '1 ação', duration: '1 hora', range: '3 m', components: 'V, S', description: 'Um truque menor. Pode criar efeitos mágicos inofensivos: acender vela, limpar objeto, criar bugigangas mágicas, etc.', damageEffect: 'Utilidade', classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago', 'Artesão Arcano'] },
  { id: 'produce-flame', name: 'Produzir Chama', level: 0, school: 'Conjuração', castingTime: '1 ação', duration: '10 min', range: 'Pessoal', components: 'V, S', description: 'Uma chama crepitante aparece em sua mão. Não causa dano mas ilumina. Alternativamente, você pode arremessá-la para causar 1d8 de dano de fogo.', damageEffect: '1d8 Fogo', attackSave: 'Ataque', classes: ['Druida'] },
  { id: 'ray-of-frost', name: 'Raio de Gelo', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '18 m', components: 'V, S', description: 'Um feixe gelado azulado estria em direção a uma criatura dentro do alcance. Faça um ataque mágico à distância. Em um acerto, 1d8 de dano frio e a velocidade da criatura é reduzida em 3 m até o início do seu próximo turno.', damageEffect: '1d8 Frio', attackSave: 'Ataque', classes: ['Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'sacred-flame', name: 'Chama Sagrada', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '18 m', components: 'V, S', description: 'Radiância em chamas desce sobre uma criatura que você possa ver dentro do alcance. O alvo deve ter sucesso em um teste de resistência de Destreza ou sofrer 1d8 de dano radiante.', damageEffect: '1d8 Radiante', attackSave: 'Res. Des', classes: ['Clérigo'] },
  { id: 'shillelagh', name: 'Cacete Mágico', level: 0, school: 'Transmutação', castingTime: '1 ação bônus', duration: '1 min', range: 'Toque', components: 'V, S, M', description: 'A madeira de um cacete ou cajado que você está segurando é imbacilizada com poder da natureza. Use Sabedoria para ataques e dano, e o dano se torna 1d8.', damageEffect: '1d8 Concussão', concentration: false, classes: ['Druida'] },
  { id: 'shocking-grasp', name: 'Toque Chocante', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: 'Toque', components: 'V, S', description: 'Relâmpago surge de sua mão. Faça um ataque mágico corpo a corpo contra o alvo. Você tem vantagem se o alvo usar armadura metálica. Em um acerto, 1d8 de dano elétrico e o alvo não pode usar reações até seu próximo turno.', damageEffect: '1d8 Elétrico', attackSave: 'Ataque', classes: ['Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'spare-dying', name: 'Estabilizar Moribundo', level: 0, school: 'Necromancia', castingTime: '1 ação', duration: 'Instantânea', range: 'Toque', components: 'V, S', description: 'Você toca uma criatura viva com 0 pontos de vida. A criatura se torna estável.', damageEffect: 'Cura', classes: ['Clérigo', 'Artesão Arcano'] },
  { id: 'thaumaturgy', name: 'Taumaturgia', level: 0, school: 'Transmutação', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'V', description: 'Manifesta um sinal menor do poder sobrenatural: voz retumba, chamas crepitam, tremores leves no chão, olhos brilham, portas se abrem.', damageEffect: 'Utilidade', classes: ['Clérigo'] },
  { id: 'toll-dead', name: 'Dobrar os Sinos', level: 0, school: 'Necromancia', castingTime: '1 ação', duration: 'Instantânea', range: '18 m', components: 'V, S', description: 'Um sino soturno ecoa em torno de uma criatura. Se falhar no teste de Constituição, sofre 1d8 de dano necrótico (1d12 se já estiver com algum dano).', damageEffect: '1d8 Necrótico', attackSave: 'Res. Con', classes: ['Clérigo', 'Bruxo'] },
  { id: 'true-strike', name: 'Golpe Certeiro', level: 0, school: 'Adivinhação', castingTime: '1 ação', duration: '1 rodada', range: '9 m', components: 'S', description: 'Você estende a mão e aponta para um alvo. Seu conhecimento místico do alvo lhe concede vantagem no seu primeiro ataque contra ele.', damageEffect: 'Vantagem', concentration: true, classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'vicious-mockery', name: 'Escárnio Vicioso', level: 0, school: 'Encantamento', castingTime: '1 ação', duration: 'Instantânea', range: '18 m', components: 'V', description: 'Você lança uma chuva de insultos contra pragas tentando abalar a concentração do alvo. O alvo que falhar num teste de Sabedoria sofre 1d4 de dano psíquico e tem desvantagem no próximo ataque.', damageEffect: '1d4 Psíquico', attackSave: 'Res. Sab', classes: ['Bardo'] },
  { id: 'word-of-radiance', name: 'Palavra de Radiância', level: 0, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '1,5 m', components: 'V, M', description: 'Uma palavra sagrada ecoa, e energia radiante irradia de você. Criaturas a sua escolha que você possa ver a 1,5 m fazem teste de Constituição ou sofrem 1d6 de dano radiante.', damageEffect: '1d6 Radiante', attackSave: 'Res. Con', classes: ['Clérigo'] },

  // ── Nível 1 ─────────────────────────────────────────────────────────────────
  { id: 'alarm', name: 'Alarme', level: 1, school: 'Abjuração', castingTime: '1 min (ritual)', duration: '8 horas', range: '9 m', components: 'V, S, M', description: 'Você define um alarme em uma área de até 6 metros cúbicos. O alarme alerta você quando uma criatura Miúda ou maior entra na área.', damageEffect: 'Alarme', ritual: true, classes: ['Mago', 'Patrulheiro', 'Artesão Arcano'] },
  { id: 'animal-friendship', name: 'Amizade com Animais', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '24 horas', range: '9 m', components: 'V, S, M', description: 'Você assegura a um animal que você não é uma ameaça. Escolha um animal que você possa ver dentro do alcance. O animal deve fazer um teste de resistência de Sabedoria.', damageEffect: 'Encantamento', classes: ['Bardo', 'Druida', 'Patrulheiro'] },
  { id: 'bane', name: 'Maldição', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'V, S, M', description: 'Até 3 criaturas a sua escolha dentro do alcance devem fazer testes de resistência de Carisma. Um alvo que falhar deve subtrair 1d4 dos testes de ataque e de resistência até a magia terminar.', damageEffect: '-1d4 Ataques', attackSave: 'Res. Car', concentration: true, classes: ['Bardo', 'Clérigo'] },
  { id: 'bless', name: 'Bênção', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'V, S, M', description: 'Você abençoa até 3 criaturas a sua escolha dentro do alcance. Sempre que um alvo fazer um teste de ataque ou de resistência antes da magia terminar, o alvo pode rolar um d4 e adicionar o número ao resultado do teste.', damageEffect: '+1d4 Ataques', concentration: true, classes: ['Clérigo', 'Paladino'] },
  { id: 'burning-hands', name: 'Mãos Flamejantes', level: 1, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: 'Pessoal (cone de 4,5m)', components: 'V, S', description: 'Enquanto você mantém seus polegares juntos e espalha seus dedos, um fino folheado de chamas jorra de suas mãos estendidas. Cada criatura em um cone de 4,5 metros deve fazer um teste de Destreza ou receber 3d6 de dano de fogo.', damageEffect: '3d6 Fogo', attackSave: 'Res. Des', classes: ['Mago', 'Feiticeiro'] },
  { id: 'charm-person', name: 'Enfeitiçar Pessoa', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 hora', range: '9 m', components: 'V, S', description: 'Você tenta enfeitiçar um humanoide que você possa ver dentro do alcance. Ele deve fazer um teste de resistência de Sabedoria ou ficar enfeitiçado por você.', damageEffect: 'Controle', attackSave: 'Res. Sab', classes: ['Bardo', 'Druida', 'Mago', 'Feiticeiro', 'Bruxo'] },
  { id: 'color-spray', name: 'Spray de Cores', level: 1, school: 'Ilusão', castingTime: '1 ação', duration: '1 rodada', range: 'Pessoal (cone de 4,5m)', components: 'V, S, M', description: 'Uma rajada de luz colorida deslumbrante emana de sua mão. Role 6d10 para saber total de PV afetados.', damageEffect: 'Cegado', classes: ['Mago', 'Feiticeiro'] },
  { id: 'command', name: 'Comandar', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 rodada', range: '18 m', components: 'V', description: 'Você fala uma palavra de comando de uma sílaba a uma criatura dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou seguir o comando no próximo turno.', damageEffect: 'Controle', attackSave: 'Res. Sab', classes: ['Clérigo', 'Paladino'] },
  { id: 'comprehend-languages', name: 'Compreender Idiomas', level: 1, school: 'Adivinhação', castingTime: '1 ação (ritual)', duration: '1 hora', range: 'Pessoal', components: 'V, S, M', description: 'Por 1 hora você entende o significado literal de qualquer língua falada que você ouvir.', damageEffect: 'Utilidade', ritual: true, classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'cure-wounds', name: 'Curar Ferimentos', level: 1, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: 'Toque', components: 'V, S', description: 'Uma criatura que você toque recupera um número de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração.', damageEffect: '1d8+mod Cura', classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Artesão Arcano'] },
  { id: 'detect-magic', name: 'Detectar Magia', level: 1, school: 'Adivinhação', castingTime: '1 ação (ritual)', duration: '10 min', range: 'Pessoal', components: 'V, S', description: 'Por 10 min você pode sentir a presença de magia em 9 m. Ação para ver uma aura ao redor de qualquer criatura ou objeto visível que carregue magia.', damageEffect: 'Utilidade', ritual: true, concentration: true, classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'disguise-self', name: 'Disfarçar-se', level: 1, school: 'Ilusão', castingTime: '1 ação', duration: '1 hora', range: 'Pessoal', components: 'V, S', description: 'Você faz com que pareça diferente até a magia terminar ou você a dispensar. Pode mudar sua aparência, incluindo roupas, armadura e equipamento.', damageEffect: 'Ilusão', classes: ['Bardo', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'divine-favor', name: 'Favor Divino', level: 1, school: 'Evocação', castingTime: '1 ação bônus', duration: '1 min', range: 'Pessoal', components: 'V, S', description: 'Sua oração infunde suas armas com poder divino. Até que a magia termine, seus ataques de arma causam 1d4 extra de dano radiante quando acertam.', damageEffect: '+1d4 Radiante', concentration: true, classes: ['Paladino'] },
  { id: 'entangle', name: 'Enredar', level: 1, school: 'Conjuração', castingTime: '1 ação', duration: '1 min', range: '27 m', components: 'V, S', description: 'Ervas e cipós brotam de um ponto de chão que você escolhe. Cada criatura na área de 6 m quadrados enraizada no chão deve ter sucesso num teste de Força ou fica restrita.', damageEffect: 'Restrito', attackSave: 'Res. For', concentration: true, classes: ['Druida', 'Patrulheiro'] },
  { id: 'faerie-fire', name: 'Fogo Feérico', level: 1, school: 'Evocação', castingTime: '1 ação', duration: '1 min', range: '18 m', components: 'V', description: 'Cada objeto em um cubo de 6 metros fica delineado em azul, verde ou violeta (sua escolha). Qualquer ataque contra uma criatura afetada tem vantagem se o atacante puder vê-la.', damageEffect: 'Vantagem em ataques', attackSave: 'Res. Des', concentration: true, classes: ['Bardo', 'Druida'] },
  { id: 'false-life', name: 'Falsa Vida', level: 1, school: 'Necromancia', castingTime: '1 ação', duration: '1 hora', range: 'Pessoal', components: 'V, S, M', description: 'Fortalecendo-se com uma energia semelhante à da morte não morta, você obtém 1d4 + 4 pontos de vida temporários por 1 hora.', damageEffect: '1d4+4 PV temp', classes: ['Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'fog-cloud', name: 'Nuvem de Névoa', level: 1, school: 'Conjuração', castingTime: '1 ação', duration: '1 hora', range: '36 m', components: 'V, S', description: 'Você cria uma névoa de 6 metros de raio centrada em um ponto dentro do alcance. A névoa obscurece a visão completamente.', damageEffect: 'Bloqueio visual', concentration: true, classes: ['Druida', 'Patrulheiro', 'Mago', 'Feiticeiro'] },
  { id: 'goodberry', name: 'Frutinhas Mágicas', level: 1, school: 'Transmutação', castingTime: '1 ação', duration: 'Instantânea', range: 'Toque', components: 'V, S, M', description: 'Até 10 frutinhas são imbacilizadas com magia por 24 horas. Cada frutinha repõe 1 PV quando comida e alimenta para o dia.', damageEffect: '1 PV por fruta', classes: ['Druida', 'Patrulheiro'] },
  { id: 'grease', name: 'Graxa', level: 1, school: 'Conjuração', castingTime: '1 ação', duration: '1 min', range: '18 m', components: 'V, S, M', description: 'Graxa escorregadia cobre o chão em um quadrado de 3 m centrado no ponto. A criatura que entrar na área ou começar o turno nela deve ter sucesso num teste de Destreza ou cair prostrada.', damageEffect: 'Prostrado', attackSave: 'Res. Des', classes: ['Mago', 'Artesão Arcano'] },
  { id: 'guiding-bolt', name: 'Raio Condutor', level: 1, school: 'Evocação', castingTime: '1 ação', duration: '1 rodada', range: '36 m', components: 'V, S', description: 'Um flash de luz jorra de seus dedos. Faça um ataque mágico à distância contra o alvo. Em um acerto, 4d6 de dano radiante e o próximo ataque contra o alvo tem vantagem.', damageEffect: '4d6 Radiante', attackSave: 'Ataque', classes: ['Clérigo'] },
  { id: 'healing-word', name: 'Palavra de Cura', level: 1, school: 'Evocação', castingTime: '1 ação bônus', duration: 'Instantânea', range: '18 m', components: 'V', description: 'Uma criatura a sua escolha que você possa ver dentro do alcance recupera PV iguais a 1d4 + seu modificador de conjuração.', damageEffect: '1d4+mod Cura', classes: ['Bardo', 'Clérigo', 'Druida'] },
  { id: 'hellish-rebuke', name: 'Represália Infernal', level: 1, school: 'Evocação', castingTime: '1 reação', duration: 'Instantânea', range: '18 m', components: 'V, S', description: 'Reação quando danificado. O atacante é envolvido em chamas infernais e deve ter sucesso num teste de Destreza ou receber 2d10 de dano de fogo.', damageEffect: '2d10 Fogo', attackSave: 'Res. Des', classes: ['Bruxo'] },
  { id: 'heroism', name: 'Heroísmo', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 min', range: 'Toque', components: 'V, S', description: 'Uma criatura voluntária que você toca é imbacilizada com bravura. Até que a magia termine a criatura é imune a condição assustado e ganha PV temporários iguais ao seu modificador de conjuração no início de cada turno.', damageEffect: 'PV temporários', concentration: true, classes: ['Bardo', 'Paladino'] },
  { id: 'hex', name: 'Hexar', level: 1, school: 'Encantamento', castingTime: '1 ação bônus', duration: '1 hora', range: '27 m', components: 'V, S, M', description: 'Você coloca uma maldição em uma criatura que você possa ver dentro do alcance. Até a magia terminar, você causa 1d6 extra de dano necrótico ao alvo quando o acertar com um ataque.', damageEffect: '+1d6 Necrótico', concentration: true, classes: ['Bruxo'] },
  { id: 'hunters-mark', name: 'Marca do Caçador', level: 1, school: 'Adivinhação', castingTime: '1 ação bônus', duration: '1 hora', range: '27 m', components: 'V', description: 'Você escolhe uma criatura que você possa ver dentro do alcance e a marca misticalmente como sua presa. Você causa 1d6 extra de dano quando acertar com um ataque de arma, e tem vantagem em testes de Percepção e Sobrevivência para localizá-la.', damageEffect: '+1d6 dano', concentration: true, classes: ['Patrulheiro'] },
  { id: 'identify', name: 'Identificar', level: 1, school: 'Adivinhação', castingTime: '1 min (ritual)', duration: 'Instantânea', range: 'Toque', components: 'V, S, M', description: 'Você escolhe um objeto que deve ser mantido em contato durante toda a conjuração. Se for um item mágico, você aprende suas propriedades mágicas.', damageEffect: 'Utilidade', ritual: true, classes: ['Bardo', 'Mago', 'Artesão Arcano'] },
  { id: 'illusory-script', name: 'Roteiro Ilusório', level: 1, school: 'Ilusão', castingTime: '1 min (ritual)', duration: '10 dias', range: 'Toque', components: 'S, M', description: 'Você escreve em papel ou superfície com tinta especial. Para todos exceto você e criaturas específicas, parece um texto confuso.', damageEffect: 'Ilusão', ritual: true, classes: ['Bardo', 'Bruxo', 'Mago'] },
  { id: 'inflict-wounds', name: 'Infligir Ferimentos', level: 1, school: 'Necromancia', castingTime: '1 ação', duration: 'Instantânea', range: 'Toque', components: 'V, S', description: 'Faça um ataque mágico corpo a corpo contra uma criatura ao alcance. Em um acerto, 3d10 de dano necrótico.', damageEffect: '3d10 Necrótico', attackSave: 'Ataque', classes: ['Clérigo'] },
  { id: 'jump', name: 'Pular', level: 1, school: 'Transmutação', castingTime: '1 ação', duration: '1 min', range: 'Toque', components: 'V, S, M', description: 'Você toca uma criatura. A distância de salto da criatura é triplicada até que a magia termine.', damageEffect: 'Mobilidade', classes: ['Druida', 'Patrulheiro', 'Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'longstrider', name: 'Passos Longos', level: 1, school: 'Transmutação', castingTime: '1 ação', duration: '1 hora', range: 'Toque', components: 'V, S, M', description: 'Você toca uma criatura. A velocidade do alvo aumenta em 3 metros até que a magia termine.', damageEffect: '+3m velocidade', classes: ['Bardo', 'Druida', 'Patrulheiro', 'Mago', 'Artesão Arcano'] },
  { id: 'mage-armor', name: 'Armadura de Mago', level: 1, school: 'Abjuração', castingTime: '1 ação', duration: '8 horas', range: 'Toque', components: 'V, S, M', description: 'Você toca uma criatura voluntária que não usa armadura, e uma força mágica protetora a circunda até que a magia termine. A CA base do alvo se torna 13 + seu modificador de Destreza.', damageEffect: 'CA 13+Des', classes: ['Mago', 'Feiticeiro'] },
  { id: 'magic-missile', name: 'Míssil Mágico', level: 1, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: '45 m', components: 'V, S', description: 'Você cria três dardos brilhantes de força mágica. Cada dardo acerta uma criatura de sua escolha dentro do alcance. Um dardo causa 1d4 + 1 de dano de força.', damageEffect: '3×(1d4+1) Força', classes: ['Mago', 'Feiticeiro'] },
  { id: 'protection-evil', name: 'Proteção do Bem e do Mal', level: 1, school: 'Abjuração', castingTime: '1 ação', duration: '10 min', range: 'Toque', components: 'V, S, M', description: 'Até que a magia termine, uma criatura voluntária que você toca é protegida contra aberrações, celestiais, elementais, fadas, demônios e mortos-vivos.', damageEffect: 'Proteção', concentration: true, classes: ['Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Bruxo', 'Mago', 'Feiticeiro'] },
  { id: 'sanctuary', name: 'Santuário', level: 1, school: 'Abjuração', castingTime: '1 ação bônus', duration: '1 min', range: '9 m', components: 'V, S, M', description: 'Você protege uma criatura contra ataques. Qualquer criatura que tente atacar o alvo deve primeiro fazer um teste de resistência de Sabedoria.', damageEffect: 'Proteção', classes: ['Clérigo'] },
  { id: 'shield', name: 'Escudo', level: 1, school: 'Abjuração', castingTime: '1 reação', duration: '1 rodada', range: 'Pessoal', components: 'V, S', description: 'Reação quando atacado. Uma barreira de força invisível aparece e deflecte o ataque. Até o início do próximo turno, você tem +5 de bônus na CA e não pode ser afetado por míssil mágico.', damageEffect: '+5 CA', classes: ['Mago', 'Feiticeiro', 'Artesão Arcano'] },
  { id: 'shield-of-faith', name: 'Escudo da Fé', level: 1, school: 'Abjuração', castingTime: '1 ação bônus', duration: '10 min', range: '18 m', components: 'V, S, M', description: 'Um campo cintilante aparece ao redor de uma criatura de sua escolha. O alvo ganha +2 de bônus na CA até que a magia termine.', damageEffect: '+2 CA', concentration: true, classes: ['Clérigo', 'Paladino'] },
  { id: 'silent-image', name: 'Imagem Silenciosa', level: 1, school: 'Ilusão', castingTime: '1 ação', duration: '10 min', range: '18 m', components: 'V, S, M', description: 'Você cria a imagem de um objeto, uma criatura ou algum outro fenômeno visível em 4,5 m³ dentro do alcance.', damageEffect: 'Ilusão', concentration: true, classes: ['Bardo', 'Mago', 'Feiticeiro'] },
  { id: 'sleep', name: 'Sono', level: 1, school: 'Encantamento', castingTime: '1 ação', duration: '1 min', range: '27 m', components: 'V, S, M', description: 'Esta magia manda criaturas em sono mágico. Role 5d8 para o total de PV que pode ser afetado.', damageEffect: 'Adormecido', classes: ['Bardo', 'Mago', 'Feiticeiro'] },
  { id: 'speak-with-animals', name: 'Falar com Animais', level: 1, school: 'Adivinhação', castingTime: '1 ação (ritual)', duration: '10 min', range: 'Pessoal', components: 'V, S', description: 'Você obtém a habilidade de compreender e verbalmente se comunicar com bestas por 10 minutos.', damageEffect: 'Comunicação', ritual: true, classes: ['Bardo', 'Druida', 'Patrulheiro'] },
  { id: 'thunderwave', name: 'Onda de Trovão', level: 1, school: 'Evocação', castingTime: '1 ação', duration: 'Instantânea', range: 'Pessoal (cubo de 4,5m)', components: 'V, S', description: 'Uma onda de força trovejante varre a partir de você. Cada criatura num cubo de 4,5 m deve ter sucesso num teste de Constituição ou sofrer 2d8 de dano de trovão e ser empurrada 3 m.', damageEffect: '2d8 Trovão', attackSave: 'Res. Con', classes: ['Bardo', 'Druida', 'Mago', 'Feiticeiro'] },
  { id: 'unseen-servant', name: 'Servo Invisível', level: 1, school: 'Conjuração', castingTime: '1 ação (ritual)', duration: '1 hora', range: '18 m', components: 'V, S, M', description: 'Você cria uma força invisível e sensível que age conforme suas ordens para 1 hora.', damageEffect: 'Utilidade', ritual: true, classes: ['Bardo', 'Bruxo', 'Mago'] },
  { id: 'witch-bolt', name: 'Raio da Bruxa', level: 1, school: 'Evocação', castingTime: '1 ação', duration: '1 min', range: '9 m', components: 'V, S, M', description: 'Um feixe de energia azul relampeja em direção a uma criatura dentro do alcance. Faça um ataque mágico. Em um acerto, 1d12 de dano elétrico, e nos turnos seguintes pode usar ação para causar 1d12 elétrico automaticamente.', damageEffect: '1d12 Elétrico', attackSave: 'Ataque', concentration: true, classes: ['Mago', 'Feiticeiro', 'Bruxo', 'Artesão Arcano'] },
  { id: 'wrathful-smite', name: 'Golpe da Ira', level: 1, school: 'Evocação', castingTime: '1 ação bônus', duration: '1 min', range: 'Pessoal', components: 'V', description: 'A próxima arremessada sua com arma causa 1d6 extra de dano psíquico. Se acertar, a criatura deve fazer um teste de Sabedoria ou ficar assustada.', damageEffect: '+1d6 Psíquico', concentration: true, classes: ['Paladino'] },
]

export { SPELLS }
export default SPELLS

export function getSpellsForClass(className: string): Spell[] {
  return SPELLS.filter(s => s.classes.includes(className))
}

export const SPELLCASTING_CLASSES = [
  'Bardo', 'Clérigo', 'Druida', 'Feiticeiro', 'Bruxo', 'Mago',
  'Paladino', 'Patrulheiro', 'Artesão Arcano'
]

// How many cantrips and level-1 spell slots each class gets at level 1
export const SPELL_SLOTS: Record<string, { cantrips: number; lvl1: number; prepared?: boolean }> = {
  'Bardo':          { cantrips: 2, lvl1: 2 },
  'Clérigo':        { cantrips: 3, lvl1: 2, prepared: true },
  'Druida':         { cantrips: 2, lvl1: 2, prepared: true },
  'Feiticeiro':     { cantrips: 4, lvl1: 2 },
  'Bruxo':          { cantrips: 2, lvl1: 2 },
  'Mago':           { cantrips: 3, lvl1: 2 },
  'Paladino':       { cantrips: 0, lvl1: 2, prepared: true },
  'Patrulheiro':    { cantrips: 0, lvl1: 2, prepared: true },
  'Artesão Arcano': { cantrips: 2, lvl1: 2, prepared: true },
}
