import { Spell } from './spells';

export const SPELLS_2014: Spell[] = [
  // ── Cantrips (Truques) 2014 ──────────────────────────────────────────────────
  { 
    id: 'acid-splash-2014', 
    name: 'Espirro Ácido', 
    level: 0, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V, S', 
    description: 'Você arremessa uma bolha de ácido. Escolha uma criatura dentro do alcance, ou escolha duas criaturas dentro do alcance que estejam a até 1,5 metro uma da outra. Um alvo deve ser bem-sucedido num teste de resistência de Destreza ou sofrerá 1d6 de dano ácido.', 
    damageEffect: '1d6 Ácido (Destreza nega)', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'blade-ward-2014', 
    name: 'Guarda da Lâmina', 
    level: 0, 
    school: 'Abjuração', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Você estende sua mão e traça um símbolo de proteção no ar. Até o final do seu próximo turno, você tem resistência contra danos de concussão, cortante e perfurante desferidos por ataques com armas.', 
    damageEffect: 'Resistência Física', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'chill-touch-2014', 
    name: 'Toque Gelado', 
    level: 0, 
    school: 'Necromancia', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Você cria uma mão esquelética e fantasmagórica no espaço de uma criatura dentro do alcance. Faça um ataque à distância com feitiço contra a criatura. Se acertar, o alvo sofre 1d8 de dano necrótico e não pode recuperar pontos de vida até o início do seu próximo turno. Se o alvo for um morto-vivo, ele terá desvantagem em jogadas de ataque contra você até o final do seu próximo turno.', 
    damageEffect: '1d8 Necrótico', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'dancing-lights-2014', 
    name: 'Luzes Dançantes', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: '36 metros', 
    components: 'V, S, M', 
    description: 'Você cria até quatro luzes do tamanho de tochas dentro do alcance, fazendo-as parecer tochas, lanternas ou esferas brilhantes que flutuam no ar. Você também pode combinar as quatro luzes em uma forma luminescente vagamente humanoide de tamanho Médio.', 
    classes: ['Bardo', 'Feiticeiro', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'druidcraft-2014', 
    name: 'Artifício de Druida', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '9 metros', 
    components: 'V, S', 
    description: 'Sussurrando aos espíritos da natureza, você cria um efeito menor: prever o clima, fazer uma flor desabrochar, criar um efeito sensorial inofensivo (como queda de folhas ou cheiro de terra) ou acender/apagar uma pequena fogueira.', 
    classes: ['Druida'] 
  },
  { 
    id: 'eldritch-blast-2014', 
    name: 'Rajada Mística', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Um feixe de energia crepitante vai em direção a uma criatura dentro do alcance. Faça um ataque à distância com feitiço contra o alvo. Se acertar, o alvo sofre 1d10 de dano de força.', 
    damageEffect: '1d10 Força', 
    classes: ['Bruxo'] 
  },
  { 
    id: 'fire-bolt-2014', 
    name: 'Raio de Fogo', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Você arremessa um estilhaço de fogo em uma criatura ou objeto dentro do alcance. Faça um ataque à distância com feitiço. Se acertar, o alvo sofre 1d10 de dano de fogo. Um objeto inflamável atingido por esta magia incendeia se não estiver sendo usado ou carregado.', 
    damageEffect: '1d10 Fogo', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'friends-2014', 
    name: 'Amigos', 
    level: 0, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: 'Pessoal', 
    components: 'S, M', 
    description: 'Você tem vantagem em todos os testes de Carisma direcionados a uma criatura de sua escolha que não seja hostil a você. Quando a magia termina, a criatura percebe que você usou magia para influenciar o humor dela e se torna hostil a você.', 
    damageEffect: 'Vantagem em Carisma', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'guidance-2014', 
    name: 'Orientação', 
    level: 0, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Você toca uma criatura disposta. Uma vez, antes da magia terminar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de habilidade de sua escolha.', 
    damageEffect: '+1d4 em teste', 
    classes: ['Clérigo', 'Druida'], 
    concentration: true 
  },
  { 
    id: 'light-2014', 
    name: 'Luz', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: 'Toque', 
    components: 'V, M', 
    description: 'Você toca um objeto que não tenha mais de 3 metros em qualquer dimensão. Até a magia acabar, o objeto emite luz brilhante num raio de 6 metros e luz penumbra por mais 6 metros adicionais.', 
    classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'mage-hand-2014', 
    name: 'Mãos Mágicas', 
    level: 0, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: '1 minuto', 
    range: '9 metros', 
    components: 'V, S', 
    description: 'Uma mão espectral e flutuante aparece num ponto à sua escolha dentro do alcance. A mão permanece pela duração ou até você dispensá-la como uma ação. Você pode usar sua ação para controlar a mão e realizar tarefas simples.', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'mending-2014', 
    name: 'Consertar', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 minuto', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Esta magia repara uma única fenda ou rasgo em um objeto que você tocar, como um elo quebrado de uma corrente, duas metades de uma chave quebrada, um manto rasgado ou um vazamento em um odre.', 
    classes: ['Bardo', 'Clérigo', 'Druida', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'message-2014', 
    name: 'Mensagem', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: '36 metros', 
    components: 'V, S, M', 
    description: 'Você aponta o dedo para uma criatura dentro do alcance e sussurra uma mensagem. O alvo (e apenas ele) ouve a mensagem e pode responder com um sussurro que apenas você ouve.', 
    classes: ['Bardo', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'minor-illusion-2014', 
    name: 'Ilusão Menor', 
    level: 0, 
    school: 'Ilusão', 
    castingTime: '1 ação', 
    duration: '1 minuto', 
    range: '9 metros', 
    components: 'S, M', 
    description: 'Você cria um som ou uma imagem de um objeto dentro do alcance que permanece pela duração. A ilusão termina se você a dispensar como uma ação ou conjurar esta magia novamente.', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'poison-spray-2014', 
    name: 'Rajada de Veneno', 
    level: 0, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '3 metros', 
    components: 'V, S', 
    description: 'Você estende sua mão em direção a uma criatura que você possa ver dentro do alcance e projeta um sopro de gás tóxico da sua palma. A criatura deve ser bem-sucedida num teste de resistência de Constituição ou sofrerá 1d12 de dano de veneno.', 
    damageEffect: '1d12 Veneno (Constituição nega)', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'prestidigitation-2014', 
    name: 'Prestidigitação', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: 'Até 1 hora', 
    range: '3 metros', 
    components: 'V, S', 
    description: 'Esta magia é um truque mágico simples que conjuradores aprendizes usam para praticar. Você cria um efeito mágico menor e inofensivo: limpar objetos, acender velas, mudar cores, etc.', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'ray-of-frost-2014', 
    name: 'Raio de Gelo', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V, S', 
    description: 'Um raio de luz azul-gelo vai em direção a uma criatura dentro do alcance. Faça um ataque à distância com feitiço contra o alvo. Se acertar, o alvo sofre 1d8 de dano de frio e seu deslocamento é reduzido em 3 metros até o início do seu próximo turno.', 
    damageEffect: '1d8 Frio + Redução de Movimento', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'resistance-2014', 
    name: 'Resistência', 
    level: 0, 
    school: 'Abjuração', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Você toca uma criatura disposta. Uma vez, antes da magia terminar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de resistência de sua escolha.', 
    damageEffect: '+1d4 em salvaguarda', 
    classes: ['Clérigo', 'Druida'], 
    concentration: true 
  },
  { 
    id: 'sacred-flame-2014', 
    name: 'Chama Sagrada', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V, S', 
    description: 'Brilho semelhante a chamas desce sobre uma criatura que você possa ver dentro do alcance. O alvo deve ser bem-sucedido num teste de resistência de Destreza ou sofrerá 1d8 de dano radiante. O alvo não recebe benefício de cobertura para este teste de resistência.', 
    damageEffect: '1d8 Radiante (Destreza nega)', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'shillelagh-2014', 
    name: 'Bordão Místico', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 ação bônus', 
    duration: '1 minuto', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'O cajado ou porrete que você segura é imbuído com o poder da natureza. Pela duração, você pode usar seu modificador de Sabedoria em vez de Força para as jogadas de ataque e dano com esta arma, e o dado de dano da arma se torna um d8.', 
    damageEffect: '1d8 + Mod Sabedoria', 
    classes: ['Druida'] 
  },
  { 
    id: 'shocking-grasp-2014', 
    name: 'Toque Chocante', 
    level: 0, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Relâmpagos saltam da sua mão para entregar um choque a uma criatura que você tentar tocar. Faça um ataque corpo a corpo com feitiço contra o alvo. Se acertar, o alvo sofre 1d8 de dano elétrico e não pode usar reações até o início do seu próximo turno.', 
    damageEffect: '1d8 Elétrico', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'spare-the-dying-2014', 
    name: 'Poupar os Moribundos', 
    level: 0, 
    school: 'Necromancia', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Você toca uma criatura viva que tenha 0 pontos de vida. A criatura torna-se estável. Esta magia não tem efeito sobre mortos-vivos ou construtos.', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'thaumaturgy-2014', 
    name: 'Taumaturgia', 
    level: 0, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: 'Até 1 minuto', 
    range: '9 metros', 
    components: 'V', 
    description: 'Você manifesta uma maravilha menor, um sinal de poder sobrenatural dentro do alcance: aumentar a voz, tremer a terra, mudar a aparência dos olhos, etc.', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'true-strike-2014', 
    name: 'Golpe Certeiro', 
    level: 0, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 rodada', 
    range: '9 metros', 
    components: 'S', 
    description: 'Você estende sua mão e aponta o dedo para um alvo no alcance. Você ganha vantagem na sua primeira jogada de ataque contra o alvo no seu próximo turno, desde que a magia não tenha terminado.', 
    damageEffect: 'Vantagem no Atk', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'], 
    concentration: true 
  },

  // ── Nível 1 2014 ─────────────────────────────────────────────────────────────
  { 
    id: 'alarm-2014', 
    name: 'Alarme', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 minuto', 
    duration: '8 horas', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Você define um alarme para intrusos. Escolha uma porta, uma janela ou uma área dentro do alcance que não seja maior que um cubo de 6 metros. Até a magia terminar, o alarme alerta você sempre que uma criatura Miúda ou maior entrar na área protegida.', 
    classes: ['Patrulheiro', 'Mago'] 
  },
  { 
    id: 'animal-friendship-2014', 
    name: 'Amizade com Animais', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: '24 horas', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Esta magia permite que você convença uma besta de que você não quer prejudicá-la. Escolha uma besta que você possa ver dentro do alcance. Ela deve ser bem-sucedida num teste de resistência de Sabedoria ou ficará enfeitiçada por você pela duração da magia.', 
    classes: ['Bardo', 'Druida', 'Patrulheiro'] 
  },
  { 
    id: 'bane-2014', 
    name: 'Perdição', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Até três criaturas à sua escolha, que você possa ver dentro do alcance, devem fazer um teste de resistência de Carisma. Sempre que um alvo que falhou no teste fizer uma jogada de ataque ou um teste de resistência antes da magia terminar, o alvo deve rolar um d4 e subtrair o número rolado do resultado.', 
    damageEffect: '-1d4 em ataques/res.', 
    classes: ['Bardo', 'Clérigo'], 
    concentration: true 
  },
  { 
    id: 'bless-2014', 
    name: 'Bênção', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 min', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Você abençoa até três criaturas, à sua escolha, dentro do alcance. Sempre que um alvo fizer uma jogada de ataque ou um teste de resistência antes da magia terminar, o alvo pode rolar um d4 e adicionar o número rolado ao resultado.', 
    damageEffect: '+1d4 em ataques/res.', 
    classes: ['Clérigo', 'Paladino'], 
    concentration: true 
  },
  { 
    id: 'burning-hands-2014', 
    name: 'Mãos Flamejantes', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Pessoal (cone de 4,5m)', 
    components: 'V, S', 
    description: 'À medida que você segura suas mãos com os polegares tocando-se e os dedos estendidos, uma folha de chamas finas brota da ponta dos seus dedos. Cada criatura em um cone de 4,5 metros deve fazer um teste de resistência de Destreza. Uma criatura sofre 3d6 de dano de fogo se falhar na resistência.', 
    damageEffect: '3d6 Fogo', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'charm-person-2014', 
    name: 'Enfeitiçar Pessoa', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: '9 metros', 
    components: 'V, S', 
    description: 'Você tenta enfeitiçar um humanoide que você possa ver dentro do alcance. Ele deve ser bem-sucedido num teste de resistência de Sabedoria ou ficará enfeitiçado por você até a magia terminar ou até você ou seus companheiros fazerem algo nocivo contra ele.', 
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'chromatic-orb-2014', 
    name: 'Orbe Cromática', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '27 metros', 
    components: 'V, S, M', 
    description: 'Você lança uma esfera de energia de 10 centímetros de diâmetro em uma criatura que você possa ver dentro do alcance. Você escolhe ácido, frio, fogo, relâmpago, veneno ou trovão para o tipo de orbe que você cria e faz um ataque à distância com feitiço contra o alvo. Se o ataque acertar, o alvo sofre 3d8 de dano do tipo escolhido.', 
    damageEffect: '3d8 dano variado', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'color-spray-2014', 
    name: 'Borrifo de Cores', 
    level: 1, 
    school: 'Ilusão', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: 'Pessoal (cone de 4,5m)', 
    components: 'V, S, M', 
    description: 'Uma matriz deslumbrante de luzes coloridas surge de sua mão. Jogue 6d10; o total é a quantidade de pontos de vida de criaturas que esta magia pode afetar. As criaturas em um cone de 4,5 metros originado em você são afetadas em ordem crescente de seus pontos de vida atuais.', 
    damageEffect: 'Cegueira por PV', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'command-2014', 
    name: 'Comando', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: '18 metros', 
    components: 'V', 
    description: 'Você fala um comando de uma única palavra para uma criatura que você possa ver dentro do alcance. O alvo deve ser bem-sucedido num teste de resistência de Sabedoria ou seguirá o comando no próximo turno dele. A magia não tem efeito se o alvo for um morto-vivo ou se o comando for diretamente nocivo a ele.', 
    classes: ['Clérigo', 'Paladino'] 
  },
  { 
    id: 'comprehend-languages-2014', 
    name: 'Compreender Idiomas', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: 'Pessoal', 
    components: 'V, S, M', 
    description: 'Pela duração da magia, você compreende o significado literal de qualquer idioma falado que você ouvir. Você também compreende qualquer idioma escrito que você vir, mas você deve tocar a superfície em que as palavras estão escritas.', 
    classes: ['Bardo', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'create-or-destroy-water-2014', 
    name: 'Criar ou Destruir Água', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Você cria ou destrói água. Criar Água: Você cria até 10 litros de água limpa dentro do alcance em um recipiente aberto. Alternativamente, a água cai como chuva em um cubo de 9 metros dentro do alcance. Destruir Água: Você destrói até 10 litros de água em um recipiente aberto dentro do alcance.', 
    classes: ['Clérigo', 'Druida'] 
  },
  { 
    id: 'cure-wounds-2014', 
    name: 'Curar Ferimentos', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Uma criatura que você tocar recupera um número de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Esta magia não tem efeito em mortos-vivos ou construtos.', 
    damageEffect: '1d8 + Mod Cura', 
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro'] 
  },
  { 
    id: 'detect-evil-and-good-2014', 
    name: 'Detectar o Bem e Mal', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 10 min', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Pela duração, você sabe se existe uma aberração, celestial, elemental, fada, ínfero ou morto-vivo dentro de 9 metros de você, bem como onde a criatura está localizada.', 
    classes: ['Clérigo', 'Paladino'], 
    concentration: true 
  },
  { 
    id: 'detect-magic-2014', 
    name: 'Detectar Magia', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 10 min', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Pela duração, você sente a presença de magia a até 9 metros de você. Se você sentir magia desta forma, você pode usar sua ação para ver uma aura tênue ao redor de qualquer criatura ou objeto visível na área que carregue magia.', 
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'disguise-self-2014', 
    name: 'Disfarçar-se', 
    level: 1, 
    school: 'Ilusão', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Você faz a si mesmo – incluindo suas roupas, armaduras, armas e outros pertences em sua pessoa – parecer diferente até a magia terminar ou até você usar sua ação para encerrá-la. Você pode parecer 30 centímetros mais baixo ou mais alto e pode parecer magro, gordo ou entre ambos.', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'dissonant-whispers-2014', 
    name: 'Sussurros Dissonantes', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V', 
    description: 'Você sussurra uma melodia discordante que apenas uma criatura à sua escolha, dentro do alcance, pode ouvir, imbuindo-a com espasmos terríveis de dor. O alvo deve fazer um teste de resistência de Sabedoria. Se falhar, sofrerá 3d6 de dano psíquico.', 
    damageEffect: '3d6 Psíquico', 
    classes: ['Bardo'] 
  },
  { 
    id: 'divine-favor-2014', 
    name: 'Favor Divino', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação bônus', 
    duration: 'Concentração, até 1 minuto', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Sua oração infunde você com poder divino. Até a magia terminar, seus ataques com armas causam 1d4 de dano radiante extra ao acertar.', 
    damageEffect: '+1d4 Radiante', 
    classes: ['Paladino'], 
    concentration: true 
  },
  { 
    id: 'entangle-2014', 
    name: 'Constrição', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 minuto', 
    range: '27 metros', 
    components: 'V, S', 
    description: 'Ervas e vinhas trepadeiras brotam do chão em um quadrado de 6 metros centrado num ponto dentro do alcance. Pela duração, essas plantas transformam o solo em terreno difícil.', 
    damageEffect: 'Área e Restrição', 
    classes: ['Druida'], 
    concentration: true 
  },
  { 
    id: 'expeditious-retreat-2014', 
    name: 'Recuo Acelerado', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 ação bônus', 
    duration: 'Concentração, até 10 minutos', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Esta magia permite que você se mova a uma velocidade incrível. Quando você conjura esta magia, e como uma ação bônus em cada um de seus turnos até a magia terminar, você pode realizar a ação de Disparar (Dash).', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'false-life-2014', 
    name: 'Falsa Vida', 
    level: 1, 
    school: 'Necromancia', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: 'Pessoal', 
    components: 'V, S, M', 
    description: 'Fortalecendo-se com uma simulação necrótica de vida, você ganha 1d4 + 4 pontos de vida temporários pela duração.', 
    damageEffect: '1d4+4 PV temp', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'feather-fall-2014', 
    name: 'Queda Suave', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 reação', 
    duration: '1 minuto', 
    range: '18 metros', 
    components: 'V, M', 
    description: 'Escolha até cinco criaturas em queda dentro do alcance. A velocidade de queda das criaturas afetadas cai para 18 metros por rodada até a magia terminar. Se a criatura aterrissar antes da magia terminar, ela não sofre dano de queda.', 
    classes: ['Bardo', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'find-familiar-2014', 
    name: 'Encontrar Familiar', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 hora', 
    duration: 'Instantânea', 
    range: '3 metros', 
    components: 'V, S, M', 
    description: 'Você adquire os serviços de um familiar, um espírito que assume uma forma animal à sua escolha: aranha, doninha, coruja, corvo, gato, falcão, morcego, peixe (polvo), rato, sapo ou serpente venenosa.', 
    classes: ['Mago'] 
  },
  { 
    id: 'fog-cloud-2014', 
    name: 'Nuvem de Névoa', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 hora', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Você cria uma esfera de névoa com 6 metros de raio centrada em um ponto dentro do alcance. A esfera se espalha dobrando esquinas e sua área é de escuridão densa. Ela dura pela duração ou até um vento moderado a disperse.', 
    classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'grease-2014', 
    name: 'Graxa', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: '1 minuto', 
    range: '18 metros', 
    components: 'V, S, M', 
    description: 'Graxa escorregadia cobre o chão em um quadrado de 3 metros centrado num ponto dentro do alcance e o torna terreno difícil pela duração. Quando a graxa aparece, cada criatura de pé em sua área deve ser bem-sucedida num teste de resistência de Destreza ou cairá caída.', 
    classes: ['Mago'] 
  },
  { 
    id: 'guiding-bolt-2014', 
    name: 'Raio Guia', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: '1 rodada', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Um flash de luz avança em direção a uma criatura à sua escolha, dentro do alcance. Faça um ataque à distância com feitiço contra o alvo. Se acertar, o alvo sofrerá 4d6 de dano radiante e a próxima jogada de ataque feita contra este alvo antes do final do seu próximo turno terá vantagem.', 
    damageEffect: '4d6 Radiante', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'hail-of-thorns-2014', 
    name: 'Chuva de Espinhos', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 ação bônus', 
    duration: 'Concentração, até 1 minuto', 
    range: 'Pessoal', 
    components: 'V', 
    description: 'A próxima vez que você acertar uma criatura com um ataque à distância com arma antes da magia terminar, a magia cria uma chuva de espinhos que brotam da arma ou munição. Além do dano normal do ataque, o alvo e cada criatura a até 1,5 metro dele devem fazer um teste de resistência de Destreza.', 
    damageEffect: '1d10 Perfurante (área)', 
    classes: ['Patrulheiro'], 
    concentration: true 
  },
  { 
    id: 'healing-word-2014', 
    name: 'Palavra Curativa', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação bônus', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V', 
    description: 'Uma criatura à sua escolha, que você possa ver dentro do alcance, recupera um número de pontos de vida igual a 1d4 + seu modificador de habilidade de conjuração. Esta magia não tem efeito em mortos-vivos ou construtos.', 
    damageEffect: '1d4 + Mod Cura', 
    classes: ['Bardo', 'Clérigo', 'Druida'] 
  },
  { 
    id: 'heroism-2014', 
    name: 'Heroísmo', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 minuto', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Uma criatura voluntária que você tocar é imbuída com bravura. Até a magia terminar, a criatura é imune a ficar amedrontada e ganha pontos de vida temporários iguais ao seu modificador de habilidade de conjuração no início de cada um dos turnos dela.', 
    damageEffect: 'Imunidade a medo e PV temp', 
    classes: ['Bardo', 'Paladino'], 
    concentration: true 
  },
  { 
    id: 'hideous-laughter-2014', 
    name: 'Riso Histérico de Tasha', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 minuto', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Uma criatura à sua escolha, que você possa ver dentro do alcance, percebe tudo como sendo hilário e cai em gargalhadas se esta magia a afetar. O alvo deve ser bem-sucedido num teste de resistência de Sabedoria ou ficará caído, incapacitado e incapaz de se levantar.', 
    classes: ['Bardo', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'hunters-mark-2014', 
    name: 'Marca do Caçador', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 ação bônus', 
    duration: 'Concentração, até 1 hora', 
    range: '27 metros', 
    components: 'V', 
    description: 'Você escolhe uma criatura que você possa ver dentro do alcance e a marca misticamente como sua presa. Até a magia terminar, você causa 1d6 de dano extra ao alvo sempre que o acertar com um ataque com arma.', 
    damageEffect: '+1d6 dano', 
    classes: ['Patrulheiro'], 
    concentration: true 
  },
  { 
    id: 'identify-2014', 
    name: 'Identificar', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 minuto', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Você escolhe um objeto que deve tocar durante toda a conjuração da magia. Se for um item mágico ou algum outro objeto imbuído de magia, você aprende suas propriedades e como usá-las.', 
    classes: ['Bardo', 'Mago'] 
  },
  { 
    id: 'illusory-script-2014', 
    name: 'Escrita Ilusória', 
    level: 1, 
    school: 'Ilusão', 
    castingTime: '1 minuto', 
    duration: '10 dias', 
    range: 'Toque', 
    components: 'S, M', 
    description: 'Você escreve em um pergaminho, papel ou qualquer outro material adequado e o imbui com uma ilusão potente que dura pela duração. Para você e quaisquer criaturas que você designar quando conjurar a magia, a escrita parece normal.', 
    classes: ['Bardo', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'inflict-wounds-2014', 
    name: 'Infligir Ferimentos', 
    level: 1, 
    school: 'Necromancia', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Toque', 
    components: 'V, S', 
    description: 'Faça um ataque corpo a corpo com feitiço contra uma criatura dentro do alcance. Se acertar, o alvo sofrerá 3d10 de dano necrótico.', 
    damageEffect: '3d10 Necrótico', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'jump-2014', 
    name: 'Salto', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: '1 minuto', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Você toca uma criatura. A distância de salto da criatura é triplicada até a magia terminar.', 
    classes: ['Druida', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'longstrider-2014', 
    name: 'Passos Longos', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Você toca uma criatura. O deslocamento do alvo aumenta em 3 metros até a magia terminar.', 
    damageEffect: '+3m deslocamento', 
    classes: ['Bardo', 'Druida', 'Patrulheiro', 'Mago'] 
  },
  { 
    id: 'mage-armor-2014', 
    name: 'Armadura de Mago', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 ação', 
    duration: '8 horas', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Você toca uma criatura voluntária que não esteja vestindo armadura e uma força mágica protetora a envolve até a magia terminar. A CA base do alvo torna-se 13 + o modificador de Destreza dele.', 
    damageEffect: 'CA 13 + Des', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'magic-missile-2014', 
    name: 'Mísseis Mágicos', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '36 metros', 
    components: 'V, S', 
    description: 'Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura à sua escolha que você possa ver dentro do alcance. Um dardo causa 1d4 + 1 de dano de força ao seu alvo. Os dardos atingem todos simultaneamente.', 
    damageEffect: '3x (1d4+1) Força', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'protection-from-evil-and-good-2014', 
    name: 'Proteção contra o Bem e Mal', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 10 minutos', 
    range: 'Toque', 
    components: 'V, S, M', 
    description: 'Até a magia terminar, uma criatura voluntária que você tocar é protegida contra certos tipos de criaturas: aberrações, celestiais, elementais, fadas, ínferos e mortos-vivos.', 
    classes: ['Clérigo', 'Paladino'], 
    concentration: true 
  },
  { 
    id: 'purify-food-and-drink-2014', 
    name: 'Purificar Alimentos', 
    level: 1, 
    school: 'Transmutação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '3 metros', 
    components: 'V, S', 
    description: 'Toda comida e bebida não mágica dentro de uma esfera de 1,5 metro de raio centrada num ponto à sua escolha, dentro do alcance, é purificada e libertada de venenos e doenças.', 
    classes: ['Clérigo', 'Druida', 'Paladino'] 
  },
  { 
    id: 'ray-of-sickness-2014', 
    name: 'Raio de Doença', 
    level: 1, 
    school: 'Necromancia', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: '18 metros', 
    components: 'V, S', 
    description: 'Um raio de energia verde doentia açoita uma criatura dentro do alcance. Faça um ataque à distância com feitiço contra o alvo. Se acertar, o alvo sofrerá 2d8 de dano de veneno e deve fazer um teste de resistência de Constituição.', 
    damageEffect: '2d8 Veneno + Envenenado', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'sanctuary-2014', 
    name: 'Santuário', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 ação bônus', 
    duration: '1 minuto', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Você protege uma criatura dentro do alcance contra ataques. Até a magia terminar, qualquer criatura que tente atacar a criatura protegida com um ataque ou uma magia prejudicial deve primeiro ser bem-sucedida num teste de resistência de Sabedoria.', 
    classes: ['Clérigo'] 
  },
  { 
    id: 'shield-2014', 
    name: 'Escudo', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 reação', 
    duration: '1 rodada', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Uma barreira invisível de força mágica aparece e protege você. Até o início do seu próximo turno, você recebe um bônus de +5 na sua CA, incluindo contra o ataque desencadeador, e você não sofre dano de mísseis mágicos.', 
    damageEffect: '+5 CA', 
    classes: ['Feiticeiro', 'Mago'] 
  },
  { 
    id: 'shield-of-faith-2014', 
    name: 'Escudo da Fé', 
    level: 1, 
    school: 'Abjuração', 
    castingTime: '1 ação bônus', 
    duration: 'Concentração, até 10 minutos', 
    range: '18 metros', 
    components: 'V, S, M', 
    description: 'Um campo cintilante aparece e envolve uma criatura à sua escolha, dentro do alcance, concedendo-lhe um bônus de +2 na CA pela duração.', 
    damageEffect: '+2 CA', 
    classes: ['Clérigo', 'Paladino'], 
    concentration: true 
  },
  { 
    id: 'silent-image-2014', 
    name: 'Imagem Silenciosa', 
    level: 1, 
    school: 'Ilusão', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 10 minutos', 
    range: '18 metros', 
    components: 'V, S, M', 
    description: 'Você cria a imagem de um objeto, de uma criatura ou de algum outro fenômeno visível, que não seja maior que um cubo de 4,5 metros. A imagem aparece num ponto dentro do alcance e dura pela duração.', 
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago'], 
    concentration: true 
  },
  { 
    id: 'sleep-2014', 
    name: 'Sono', 
    level: 1, 
    school: 'Encantamento', 
    castingTime: '1 ação', 
    duration: '1 minuto', 
    range: '27 metros', 
    components: 'V, S, M', 
    description: 'Esta magia coloca as criaturas num adormecimento mágico. Jogue 5d8; o total é a quantidade de pontos de vida de criaturas que esta magia pode afetar. As criaturas num raio de 6 metros, centradas num ponto à sua escolha dentro do alcance, são afetadas.', 
    damageEffect: 'Sono por PV', 
    classes: ['Bardo', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'speak-with-animals-2014', 
    name: 'Falar com Animais', 
    level: 1, 
    school: 'Adivinhação', 
    castingTime: '1 ação', 
    duration: '10 minutos', 
    range: 'Pessoal', 
    components: 'V, S', 
    description: 'Pela duração, você adquire a habilidade de compreender e se comunicar verbalmente com bestas. O conhecimento e a consciência de muitas bestas são limitados pela inteligência delas.', 
    classes: ['Bardo', 'Druida', 'Patrulheiro'] 
  },
  { 
    id: 'thunderwave-2014', 
    name: 'Onda de Trovão', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Instantânea', 
    range: 'Pessoal (cubo de 4,5m)', 
    components: 'V, S', 
    description: 'Uma onda de força trovejante irradia de você. Cada criatura num cubo de 4,5 metros originado em você deve fazer um teste de resistência de Constituição. Se falhar, uma criatura sofrerá 2d8 de dano de trovão e será empurrada 3 metros.', 
    damageEffect: '2d8 Trovão', 
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Mago'] 
  },
  { 
    id: 'unseen-servant-2014', 
    name: 'Servo Invisível', 
    level: 1, 
    school: 'Conjuração', 
    castingTime: '1 ação', 
    duration: '1 hora', 
    range: '18 metros', 
    components: 'V, S, M', 
    description: 'Esta magia cria uma força invisível, sem mente e sem forma, que realiza tarefas simples ao seu comando até a magia terminar. O servo surge num espaço vazio no chão, dentro do alcance.', 
    classes: ['Bardo', 'Bruxo', 'Mago'] 
  },
  { 
    id: 'witch-bolt-2014', 
    name: 'Relâmpago de Bruxa', 
    level: 1, 
    school: 'Evocação', 
    castingTime: '1 ação', 
    duration: 'Concentração, até 1 minuto', 
    range: '9 metros', 
    components: 'V, S, M', 
    description: 'Um feixe de energia azul crepitante lança-se em direção a uma criatura dentro do alcance, formando um arco de relâmpago entre você e o alvo. Faça um ataque à distância com feitiço contra a criatura. Se acertar, o alvo sofrerá 1d12 de dano elétrico.', 
    damageEffect: '1d12 Elétrico contínuo', 
    classes: ['Feiticeiro', 'Bruxo', 'Mago'], 
    concentration: true 
  },
];

export const SPELL_SLOTS_2014: Record<string, any> = {
  'Bardo': {
    1: { cantrips: 2, known: 4, slots: [2, 0, 0, 0, 0] },
    2: { cantrips: 2, known: 5, slots: [3, 0, 0, 0, 0] },
  },
  'Clérigo': {
    1: { cantrips: 3, prepared: 'Wis + Lvl', slots: [2, 0, 0, 0, 0] },
    2: { cantrips: 3, prepared: 'Wis + Lvl', slots: [3, 0, 0, 0, 0] },
  },
  'Druida': {
    1: { cantrips: 2, prepared: 'Wis + Lvl', slots: [2, 0, 0, 0, 0] },
    2: { cantrips: 2, prepared: 'Wis + Lvl', slots: [3, 0, 0, 0, 0] },
  },
  'Feiticeiro': {
    1: { cantrips: 4, known: 2, slots: [2, 0, 0, 0, 0] },
    2: { cantrips: 4, known: 3, slots: [3, 0, 0, 0, 0] },
  },
  'Bruxo': {
    1: { cantrips: 2, known: 2, slots: [1, 0, 0, 0, 0] }, // Pact Magic slots
    2: { cantrips: 2, known: 3, slots: [2, 0, 0, 0, 0] },
  },
  'Mago': {
    1: { cantrips: 3, prepared: 'Int + Lvl', slots: [2, 0, 0, 0, 0] },
    2: { cantrips: 3, prepared: 'Int + Lvl', slots: [3, 0, 0, 0, 0] },
  },
  'Paladino': {
    1: { cantrips: 0, slots: [0, 0, 0, 0, 0] },
    2: { cantrips: 0, prepared: 'Cha + Lvl/2', slots: [2, 0, 0, 0, 0] },
  },
  'Patrulheiro': {
    1: { cantrips: 0, slots: [0, 0, 0, 0, 0] },
    2: { cantrips: 0, known: 2, slots: [2, 0, 0, 0, 0] },
  },
  'Artesão Arcano': {
    1: { cantrips: 2, prepared: 'Int + Lvl/2', slots: [2, 0, 0, 0, 0] },
  }
};
